### ISSUE TITLE
Depend on new mongoose-shortid

### ISSUE THREAD

**Issue by matthewadams** [SciSpike/yaktor#13]
Yaktor currently depends on https://github.com/SciSpike/mongoose-shortid, which is a forked version of https://github.com/lucasrudi/mongoose-shortid, which is a forked version of https://github.com/jjwchoy/mongoose-shortid.

If we can get jjwchoy to accept a pull request, then yaktor can depend on that version of `mongoose-shortid`.  If not, we can rename https://github.com/SciSpike/mongoose-shortid to be something else, publish to npm, and have yaktor depend on it.

**Comment by jkamke** [comment]
used mongoose-shortid-nodeps
