### ISSUE TITLE
in docker-compose.yml - image: ${APP_NAME}:${APP_TAG} doesn't work with tags with /'s (like git-flow style feature tags for example)

### ISSUE THREAD

**Issue by gacord23** [SciSpike/yaktor#17]

**Comment by matthewadams** [comment]
While this might be a bug in `docker-compose.yml`, it's also a limitation of Docker: see the first paragraph at https://docs.docker.com/engine/reference/commandline/tag/

**Comment by gacord23** [comment]
I'm aware it's a limitation of docker.  I would say, if we are going to use a tag that is perfectly acceptable to git but not to docker, then we need to clean it first.

**Comment by matthewadams** [comment]
This is no longer an issue, since we're not using git to identify a tag value anymore.  The user should set their own `APP_TAG` environment variable with their own cleansing if they don't want to take the default of `latest`.
