### ISSUE TITLE
Redirect http://yaktor.{io,com,org,actor}

### ISSUE THREAD

**Issue by matthewadams** [SciSpike/yaktor#5]
...to the right place (scispike.com/yaktor)

**Comment by jkamke** [comment]
yaktor.io points to s3 bucket with docs and eclipse plugin site

**Comment by matthewadams** [comment]
@jkamke, can you please add entries to redirect yaktor.com & yaktor.org to yaktor.io? I've already forwarded yaktor.actor to yaktor.io.

**Comment by jkamke** [comment]
now...


[www.yaktor.com](http://www.yaktor.com) -> [yaktor.com](http://yaktor.com) -> [yaktor.io](http://yaktor.io)
[www.yaktor.org](http://www.yaktor.org) -> [yaktor.org](http://yaktor.org) -> [yaktor.io](http://yaktor.io)

and added missing:
[www.yaktor.io](http://www.yaktor.io) -> [yaktor.io](http://yaktor.io)

NOTE: bucket redirect seems to only work with the long names like www.yaktor.io.s3-website-us-west-2.amazonaws.com
